name: CD Workflow

on:
  push:
    branches:
      - main

jobs:
  cd-deploy-test:
    name: Deploy to TEST
    runs-on: ubuntu-latest
    environment: dbw-test
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'
      
      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel build

      - name: Build wheel artifact
        run: |
          python -m build
          ls dist

      - name: Configure Databricks
        run: |
          # write out the profile (here called "test")
          cat <<EOF > ~/.databrickscfg
          [test]
          host = https://adb-7405614166452217.17.azuredatabricks.net/
          azure_tenant_id = ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id = ${{ secrets.AZURE_CLIENT_ID }}
          azure_client_secret = ${{ secrets.AZURE_CLIENT_SECRET }}
          EOF

      - name: Deploy to TEST
        run: |
          databricks bundle deploy \
            --target test \
            --profile test

  cd-deploy-prod:
    name: Deploy to PROD
    needs: cd-deploy-test
    runs-on: ubuntu-latest
    environment: dbw-prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12.3'

      - name: Set up Java 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Databricks CLI
        run: curl -fsSL https://raw.githubusercontent.com/databricks/setup-cli/main/install.sh | sh

      - name: Install Dependencies
        run: |
          pip install --upgrade pip
          pip install setuptools wheel build

      - name: Build wheel artifact
        run: |
          python -m build
          ls dist

      - name: Configure Databricks
        run: |
          # write out the profile (here called "prod")
          cat <<EOF > ~/.databrickscfg
          [prod]
          host = https://adb-7405610949391953.13.azuredatabricks.net/
          azure_tenant_id = ${{ secrets.AZURE_TENANT_ID }}
          azure_client_id = ${{ secrets.AZURE_CLIENT_ID }}
          azure_client_secret = ${{ secrets.AZURE_CLIENT_SECRET }}
          EOF

      - name: Deploy to PROD
        run: |
          databricks bundle deploy \
            --target prod \
            --profile prod
